### ISSUE TITLE
AMA 林宏宇

### ISSUE THREAD

**Issue by TechQuery** [freeCodeCamp-China/activity#1]
- [x] 采访嘉宾 @Skylin0909
- [x] [宣传文案](https://mp.weixin.qq.com/s/O9pVx_dH0hlPJlKKCpan7Q) @miyaliu666
- [x] 主持人 @TechQuery

**Comment by TechQuery** [comment]
## 水歌发问

1. **技术社区**对你职业成长的影响
2. 更看好**个人技术品牌**还是技术社区？
3. 给 freeCodeCamp 一些建议
4. 忙于业务的一线工程师如何看待**开源项目**？

**Comment by evan-lin9** [comment]
## 公众号问题收集
1. 大专生，计算机专业，已经自学了一段时间前端，但是总感觉啥也不会，啥也记不住，但是也用html+css仿写过小米官网，却还是感觉没有学到什么，看了别人的一些问题什么的也答不上来，很迷茫，感觉这根本找不到工作一样，想要知道到底要怎么做呢？
2. 我想知道平时工作中不怎么用的技术栈，怎么样看自己到什么水平了，怎么推广到项目去
3. 我是13年毕业的，中途从事其他工作后，转行做前端开发已经两三年了，但是感觉要学的技术太多，自己的基础也不是很好，现在没有个学习方向，这也想学那也想学，到头来啥也没记住，很苦恼，请问有好的学习方法吗？
4. 我也是一名机械类专业转行的前端，目前从事工作有年多点，现在遇到了个很苦恼的问题，我不知道是该多学习一点前端知识还是学习后台语言，而且不是相关专业所以基础非常不扎实，很不利于后期的发展，如果想要做出点成绩我该从哪里做起，感觉要学的东西很多。非常苦恼，我想知道当初您是怎么学习的。
5.  我是文科生，大学学过一点 VB，英语四级水平，有设计基础，平时工作中用表格比较多，想学点编程提高工作效率，请问嘉宾可以推荐些学习资源吗？最好是免费的可以自己安排学习进度的。

**Comment by evan-lin9** [comment]
## B 站小伙伴发问
1. 已经毕业后接触程序，英语基础不好，是从头学易，还是跟风学py
2. 大专生大一，已经决定从电子信息转到计算机了，一口气学完了c，接下来就很迷茫，又想学算法，又想再学一门语言，学算法数学基础又不够，很纠结
