### ISSUE TITLE
工具软件擂台 —— 软粉 vs 果粉

### ISSUE THREAD

**Issue by TechQuery** [freeCodeCamp-China/activity#2]

**Comment by S1ngS1ng** [comment]
# Windows Outline
1. 兼容性，跨设备 (OEM)
2. ~~开箱即用~~直观，平铺, intuitive (对比 adobe，驾驶舱)
3. Ribbon & Context toolbar (feat. medium, android) => 交互创新
4. 去主菜单化

# macOS Outline
1. 自有硬件
2. Top menu, intuitive
3. 简化界面 (对比 adobe，驾驶舱，grouping 逻辑)
4. Design, multi-media

# Random
## GUI
- 焦点 Focus point
## Windows Vista
- .net, Long Horn
## Metro VS Modern UI
- Ease of use
- Gnarly
- For mobile
- 开箱即用: out of box
## Search box

# Built-in
## Finder VS File Explorer
- Ribbon design
- Context menu: Ease of use
- Context menu: position, global vs app-specific
## Entrypoint
- 找任何东西：Spotlight/Alfred VS Everything/Wox?
- 找软件：Launchpad VS 开始菜单？
- 开始菜单：“一切皆对象”，适配
- 快捷方式
## Widget
- -1 屏：Dashboard (R.I.P.)
- 通知中心：Notification Center
- “小组件”：Widgets in Big Sur
## Apps (hands-off) && Programs
### "Office" suite
- iWork VS Office
- Notes VS OneNote
- Mail/Spark/Air Mail VS Outlook
- Calendar/Reminders VS ?
### Browser
- Safari VS Edge
- Chrome (incl. Vivaldi, etc.)
### Phone/Device Syncing
- Phone call & Facetime
- 短信：Messages (Big Sur)
- 联系人：Contacts
- 照片：Photos/Photo Booth
- 智能家居：Home (Big Sur)
- Music, Podcast, Apple TV, News and Stocks
### Multimedia
- 截图录屏工具：Screenshot VS PicPick?
- 声音：GarageBand/Logic Pro X VS ?
- 视频：iMovie/Final Cut Pro X VS ?
### Voice Assistant
- Siri VS Cortana
- Google VS 小米
### Dictionary
- 字典工具：Dictionary (N.B. force touch) VS ?
## Utility
### Automation
- Automator VS ?
- Script Editor VS ?
### Password Management
- 密码管理，云端同步：Keychain Access
### Audio
- Midi 设置：Midi
### Design
- 颜色工具：Digital Color Meter/Color Sync Utilities
# 开发相关
## Terminal and env
- iTerm/Terminal VS Windows Terminal/命令提示符
- Built in Z Shell
- Built in Perl, python, git ...
- Apple specific options
## Editor and IDE (note: language specific)
- XCode VS Visual Studio
- Jetbrains
- VSCode

**Comment by S1ngS1ng** [comment]
# New laptop
# Must-know feature
- 开始菜单
- 快捷键
# 开发环境搭建、日常使用
- Chocolatey (git, chrome, nodejs)
- ~~terminal~~git-bash
- Everything
- WPS

**Comment by TechQuery** [comment]
![87f120ee35abbb1708b51e63e179fb1](https://user-images.githubusercontent.com/19969570/178290832-46a0729c-dab1-4cc0-a664-ea74928e4aef.jpg)
