### ISSUE TITLE
山寨 SpaceX 3D UI

### ISSUE THREAD

**Issue by TechQuery** [freeCodeCamp-China/activity#3]
- 主讲人：@LiJiahaoCoder
- 代码库：https://github.com/LiJiahaoCoder/SpaceX-UI
- 时间：7月11日（周六）下午 3:00～5:00

**Comment by LiJiahaoCoder** [comment]
项目已部署Github Page：https://lijiahaocoder.github.io/SpaceX-UI/

**Comment by TechQuery** [comment]
duplicated with #10
