### ISSUE TITLE
大学生 刷题直播

### ISSUE THREAD

**Issue by TechQuery** [freeCodeCamp-China/activity#6]
1. CP 结对刷题
2. 定期直播分享各组解法
3. 同期嘉宾主题分享

**Comment by JJJinXxxx** [comment]
### 夏日大作战之——freeCodeCamp暑期学习打卡
滴！学习卡！
在 freeCodeCamp 和全球 400 万人一起免费学编程！
2020年暑假如约而至，都说假期是最好的超车道，现在有机会通过freeCodeCamp (简称:FCC)渐进的学习Web相关课程，提高自己的技术实力，与FCC一起实现弯道超车， 你确定不试试吗？freeCodeCamp暑期学习打卡等你来！
什么是FCC？
FCC，一个学习Web全栈的平台，提供了大量免费的编程教程，包括交互式课程、视频课程和文章。在这里可以渐进、完整地学习Web相关知识架构。
FCC训练营助你踏入Web世界的大门，小白变强者，强者变大佬。心动不如行动，快来报名吧！  

- 活动时间：
2020.7.31 - 8.31（共30天）

- 参与方式：
【活动qq群号】 646273183 
扫描二维码加群（微信或QQ）→ 填写报名表 → 加入【小打卡】“重庆大学夏日大作战 ” 活动 

- 面向对象：

1. 各大高校对前端技术感兴趣的学生，不限专业不限年级
2. 刚刚结束高考，暑假闲置在家里的且想要学习前端知识高中毕业生
3. 各大企业想要拓展职业技能在职员工
4. 刚毕业想要应聘网络工程师相关职业的毕业生
5. 

- 活动方式: 

**选择挑战模式** ：个人赛 or 战队赛（可同时报名个人及组合，可入群寻觅队友再组合报名）
1、个人报名
2、男女混合双打，两人一共打卡天数达到21天即可。
3、多人小组（至少4人），互相监督，每天有超过3/4的人打卡，即算小组打卡成功
**网上学习** ：学习FCC网址内置课程与题目
**线上打卡** ：完成课程与题目后，在微信群内打卡，总打卡天数要达到21天（时限为一个月内），具体打卡流程见群内文件《夏日大作战作战手册》。
**集中答疑** ：每天晚上19：00-21:00开展集中答疑，提交自己当天遇到的问题，有技术人员给予解答（不仅限于技术问题）
**英语下午茶** ：较强英语能力也是程序员必备素养，邀请到本校英语学院“猫月的英语沙龙客厅”创办者，为大家补充每日一题
**每周讲座** ：联合FCC直播在b站开展专题讲座4场

另外，我们还准备了丰富的奖品。

- 转发说说积赞奖励

1、满49，重庆大学纸胶带
2、满69，重庆大学钥匙背包小挂件
3、满109，定制鼠标垫
 

- 打卡完成奖励

1、打卡21天：
键盘的键帽一个 + 校级证书
2、打卡30天（全勤）：
自选任一图灵出版社的实体书籍 + 校级证书
3、优秀营员5人
freeCodeCamp限量版书包 + 校级证书

- 打卡形式： 

1、文字型：“年轻人的天是没有边的！” 
2、代码型：一行代码
3、成果记录型：记录下当天的学习时间/学习量等
4、笔记型：整理总结今日所学

承办方：重庆大学网络信息协会&新闻网技术部
【关注我们】网络信息协会qq群：667830541

也许就是这个假期，小白变强者，强者变大佬，快来和我们一起打卡吧！

**Comment by TechQuery** [comment]
duplicate with #12
