### ISSUE TITLE
大规模PDNS数据中的恶意域名识别和异常事件挖掘

### ISSUE THREAD

**Issue by demongodYY** [freeCodeCamp-China/activity#9]
- 形式：讲师授课
- 讲师：何直泽 @PeterHo
- 时间：2020年7月25日（周六）19:00~21:00

> 何直泽, 从事网络安全相关工作多年，现任奇安信技术研究院研究员, 目前主要关注恶意域名识别。

> 目前使用机器学习对恶意域名识别分类的尝试主要基于监督学习。但问题在于有高质量标签的数据很少，而且根据观察的角度不同，恶意域名的分类方式也多种多样。
若基于无监督学习来做聚类，结果准确度不高，且很难评估聚类效果。
而半监督学习，作为一种在有标签数据+无标签数据混合成的训练数据中使用的机器学习算法，在无标签数据比有标签数据多得多的场景下有较好的表现效果。

**Comment by miyaliu666** [comment]
已发布视频 https://www.bilibili.com/video/BV17t4y1D72s
